# DASHBOARDS

Creación de tablas de Dashboard en My SQL desde Python

In [29]:
import pandas as pd

df = pd.read_csv("customer_analytics_dataset.csv")

df.head()

,age,gender,country,city,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,...,credit_balance,churned,signup_quarter,engagement_score,friction_index,inactivity_score,risk_score,risk_segment,predicted_churn_rule_based,customer_id
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,2278.0,0,Q1,0.338537,0.313677,0.118467,0.403989,Medium Risk,0,1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,3028.0,0,Q4,0.535744,0.274211,0.247387,0.343523,Low Risk,0,2
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,2317.0,0,Q4,0.170501,0.440787,0.038328,0.495657,High Risk,0,3
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,2674.0,0,Q1,0.541906,0.249609,0.163763,0.311541,Low Risk,0,4
4,35.0,Male,India,Delhi,3.1,29.0,51.4,8.4,19.1,9.0,...,5354.0,0,Q4,0.712408,0.129161,0.254355,0.223832,Low Risk,0,5

In [30]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Leticia.1@localhost:3306/ecommerce_db")

df = pd.read_sql("SELECT * FROM analytics_customer_360", engine)

print(df.head())

   customer_id   age  gender country        city  membership_years  \
0            1  43.0    Male  France   Marseille               2.9
1            2  36.0    Male      UK  Manchester               1.6
2            3  45.0  Female  Canada   Vancouver               2.9
3            4  56.0  Female     USA    New York               2.6
4            5  35.0    Male   India       Delhi               3.1

  signup_quarter  login_frequency  session_duration_avg  pages_per_session  \
0             Q1             14.0                  27.4                6.0
1             Q4             15.0                  42.7               10.3
2             Q4             10.0                  24.8                1.6
3             Q1             10.0                  38.4               14.8
4             Q4             29.0                  51.4                8.4

   ...  returns_rate  customer_service_calls  cart_abandonment_rate  \
0  ...           2.0                     9.0                   50.6
1  ...           9.2                     7.0                   37.7
2  ...          11.5                     4.0                   70.9
3  ...           5.4                     2.0                   41.7
4  ...           5.5                     1.0                   19.1

   days_since_last_purchase  engagement_score  friction_index  \
0                      34.0          0.338537        0.313677
1                      71.0          0.535744        0.274211
2                      11.0          0.170501        0.440787
3                      47.0          0.541906        0.249609
4                      73.0          0.712408        0.129161

   inactivity_score  risk_score  risk_segment  predicted_churn_rule_based
0          0.118467    0.403989   Medium Risk                           0
1          0.247387    0.343523      Low Risk                           0
2          0.038328    0.495657     High Risk                           0
3          0.163763    0.311541      Low Risk                           0
4          0.254355    0.223832      Low Risk                           0

[5 rows x 31 columns]

Cargando tabla principal desde my SQL

In [33]:
import pandas as pd
from sqlalchemy import create_engine, text

# conexión
engine = create_engine("mysql+pymysql://root:Leticia.1@localhost/ecommerce_db")

In [34]:
#Cargando datos desde MySQL
df = pd.read_sql("SELECT * FROM ecommerce_customers", engine)

df.head()

,age,gender,country,city,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,...,credit_balance,churned,signup_quarter,engagement_score,friction_index,inactivity_score,risk_score,risk_segment,predicted_churn_rule_based,customer_id
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,2278.0,0,Q1,0.338537,0.313677,0.118467,0.403989,Medium Risk,0,1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,3028.0,0,Q4,0.535744,0.274211,0.247387,0.343523,Low Risk,0,2
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,2317.0,0,Q4,0.170501,0.440787,0.038328,0.495657,High Risk,0,3
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,2674.0,0,Q1,0.541906,0.249609,0.163763,0.311541,Low Risk,0,4
4,35.0,Male,India,Delhi,3.1,29.0,51.4,8.4,19.1,9.0,...,5354.0,0,Q4,0.712408,0.129161,0.254355,0.223832,Low Risk,0,5

In [35]:
def save_table(df_table, table_name):

    with engine.connect() as conn:
        conn.execute(text(f"DROP TABLE IF EXISTS {table_name}"))

    df_table.to_sql(
        table_name,
        con=engine,
        index=False
    )

    print(f"Tabla creada: {table_name}")

In [36]:
pd.read_sql("SELECT * FROM dashboard_risk_segments", engine)

  risk_segment  total_customers      avg_ltv  avg_purchases
0  Medium Risk            16666  1349.864089      12.162360
1     Low Risk            16667  2053.936818      18.542467
2    High Risk            16667   918.072524       8.629843

In [37]:
def save_table(df_table, table_name):

    with engine.connect() as conn:
        conn.execute(text(f"DROP TABLE IF EXISTS {table_name}"))

    df_table.to_sql(
        table_name,
        con=engine,
        index=False
    )

    print(f"Tabla creada: {table_name}")

In [38]:
# Crear columna total_spent si no existe
if "total_spent" not in df.columns:
    df["total_spent"] = df["average_order_value"] * df["total_purchases"]

DASHBOARD 1 - SEGMENTOS DE RIESGO 
Creada en MySQL

Dashboard 2 - Clientes por país

In [39]:
customers_country = (
    df.groupby("country")
    .size()
    .reset_index(name="customers")
    .sort_values("customers", ascending=False)
)

save_table(customers_country, "dashboard_customers_country")

Tabla creada: dashboard_customers_country

Dashboard 3 - Clientes por género

In [40]:
customers_gender = (
    df.groupby("gender")
    .size()
    .reset_index(name="customers")
)

save_table(customers_gender, "dashboard_customers_gender")

Tabla creada: dashboard_customers_gender

Dahboard 4 - Distribución por edad

In [41]:
customers_gender = (
    df.groupby("gender")
    .size()
    .reset_index(name="customers")
)

save_table(customers_gender, "dashboard_customers_gender")

Tabla creada: dashboard_customers_gender

Dashboard 5 - Promedio gasto por segmento

In [42]:
# Crear columna total_spent si no existe
if "total_spent" not in df.columns:
    df["total_spent"] = df["average_order_value"] * df["total_purchases"]

Esto calcula:
gasto total = valor promedio de oedido x nùmero de compras

In [43]:
#Creación de Dashboard
# Crear columna total_spent si no existe
if "total_spent" not in df.columns:
    df["total_spent"] = df["average_order_value"] * df["total_purchases"]

Dashboard 6 - Inactividad por riesgo

In [45]:
#Dashboard 6- Inactividad por riesgo
inactivity_segment = (
    df.groupby("risk_segment")["inactivity_score"]
    .mean()
    .reset_index()
)

save_table(inactivity_segment, "dashboard_inactivity_by_segment")

Tabla creada: dashboard_inactivity_by_segment